FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y automake pkg-config libtool autogen libpcap-dev build-essential


COPY . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure --disable-local-libopts
RUN make -j8
